### ISSUE TITLE
Exclude feature "date" from moving average computation

### ISSUE THREAD

**Issue by davihdsantos** [Natalnet/np-datamanager#2]
at the moment it seems the endpoint returns the moving average of any features in the field "feature". for example, http://ncovid.natalnet.br/datamanager/repo/p971074907/path/brl/feature/newDeaths:newCases/begin/2020-01-01/end/2022-02-21/period/7/as-json returns the moving average of newDeaths and newCases.

but when "date" is added the endpoint tries to find the moving average of date -> http://ncovid.natalnet.br/datamanager/repo/p971074907/path/brl/feature/date:newDeaths:newCases/begin/2020-01-01/end/2022-02-21/period/7/as-json

**Comment by juliogcosta** [comment]
ok, done.
