### ISSUE TITLE
moving average endpoint return format is different from older version

### ISSUE THREAD

**Issue by davihdsantos** [Natalnet/np-datamanager#3]
http://ncovid.natalnet.br/datamanager/repo/p971074907/path/brl/feature/date:newDeaths:newCases/begin/2020-01-01/end/2022-02-21/as-json returns [{feature1: value1, feature2: value1, etc}, {feature1: value2, feature2: value2, etc}] 

while

http://ncovid.natalnet.br/datamanager/repo/p971074907/path/brl/feature/newDeaths:newCases/begin/2020-01-01/end/2022-02-21/period/7/as-json returns {feature1: [all values], fetaure2: [all values]}

**Comment by juliogcosta** [comment]
solved! now the return of this endpoint is the same as the other endpoints. get new release.

**Comment by davihdsantos** [comment]
http://ncovid.natalnet.br/datamanager/repo/p971074907/path/brl:rn/features/date:newCases/window-size/7/as-json this endpoint is not working in the latest version of np.datamanager.jar. 

![image](https://user-images.githubusercontent.com/2212793/168169487-b7317f4b-7a75-4baf-8bb3-43821349df11.png)

**Comment by juliogcosta** [comment]
you asked for add the timeseries date range to the request. add 'begin' and 'end' variables to the url, after the window size value. example: http://ncovid.natalnet.br/datamanager/repo/p971074907/path/brl:rn/features/date:newCases/window-size/7/begin/2022-01-03/end/2022-02-03/as-json.

**Comment by davihdsantos** [comment]
> you asked for add the timeseries date range to the request. add 'begin' and 'end' variables to the url, after the window size value. example: http://ncovid.natalnet.br/datamanager/repo/p971074907/path/brl:rn/features/date:newCases/window-size/7/begin/2022-01-03/end/2022-02-03/as-json.

nice!
